[package]
name = "glfw"
version = "0.0.4"
authors = ["The glfw-rs developers."]
description = "GLFW3 bindings and idiomatic wrapper for Rust."
keywords = ["windowing", "opengl"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bjz/glfw-rs"

[features]
default = ["glfw-sys"]

[dependencies]
semver = "*"
log = "*"
bitflags = "*"
libc = "*"

[dependencies.glfw-sys]
glfw-sys = "*"
optional = true
